push-to-github:
  stage: deploy
  image: bitnami/git:2.39.1
  only:
    - main
  script:
    - git --version
    - echo "https://bachhs:$GITHUB_TOKEN@github.com" > ~/.git-credentials
    - git config credential.helper 'store --file ~/.git-credentials'
    - git config remote.github.url >&- || git remote add github https://github.com/bachhs/dtcsolution-ckan.git
    - git push github HEAD:main
