default:
  image: node:16.16.0

# deploy_preview:
#   stage: deploy
#   except:
#     - vue3-version
#   script:
#     - npm install --global vercel
#     - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
#     - vercel build --token=$VERCEL_TOKEN
#     - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

# deploy_production:
#   stage: deploy
#   only:
#     - vue3-version
#   script:
#     - npm install --global vercel
#     - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
#     - vercel build --prod --token=$VERCEL_TOKEN
#     - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

push-to-github:
  stage: deploy
  image: alpine/git:2.36.3
  only:
    - vue3-version
  script:
    - echo "https://bachhs:$GITHUB_TOKEN@github.com" > ~/.git-credentials
    - git config credential.helper 'store --file ~/.git-credentials'
    - git push github HEAD:vue3-version
